wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1676239343.044408
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      - 35
      4: 3.9.13
      5: 0.13.6
      8:
      - 5
